### ISSUE TITLE
New Relic is missing ebuild

### ISSUE THREAD

**Issue by pucowanje** [nexylan/nexylan-gentoo-overlay#2]
It says you've updated New Relic 8 days ago. I can also see this in the manifest file but for some reason there is no ebuild. I would love to have a running ebuild and if you already got one i would love to use yours. Would you mind adding it?

**Comment by gallart** [comment]
Hello,

This has been fixed in my latest commit : https://github.com/nexylan/nexylan-gentoo-overlay/commit/51a7a22bc8b7dbf94749b83ee521152adb07edf1

Sorry about that.

Gaëtan
