### ISSUE TITLE
dev-db/xtradb-cluster-5.7.18 compile failure

### ISSUE THREAD

**Issue by UnixRonin** [nexylan/nexylan-gentoo-overlay#4]
dev-db/xtradb-cluster-5.7.18 fails during compilation.
Using 'ebuild .../xtradb-cluster-5.7.18.ebuild compile':

g++ -o gcs/src/.garb/gcs_group.o -c -Weffc++ -Wold-style-cast -pipe -Wno-long-long -Wno-deprecated -ansi -DPERCONA_INNODB_VERSION=rel15 -march=amdfam10 -O2 -pipe -mfpmath=sse -mcx16 -mpopcnt -g -O3 -fno-omit-frame-pointer -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_SYSTEM_ASIO -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -Wno-variadic-macros -Wno-old-style-cast -Wno-missing-field-initializers -Wno-effc++ -DGCS_FOR_GARB -Igalerautils/src -Igcomm/src -Igcache/src gcs/src/gcs_group.cpp
gcs/src/gcs_node.cpp: In function 'void gcs_node_update_status(gcs_node_t*, const gcs_state_quorum_t*)':
gcs/src/gcs_node.cpp:176:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (quorum->version >= 4) {
             ^~
gcs/src/gcs_node.cpp:184:9: note: here
         case GCS_NODE_STATE_SYNCED:
         ^~~~
cc1plus: all warnings being treated as errors
scons: *** [gcs/src/.garb/gcs_node.o] Error 1
scons: building terminated because of errors.
cp: cannot stat 'garb/garbd': No such file or directory
cp: cannot stat 'libgalera_smm.so': No such file or directory
>>> Source compiled.

Using 'ebuild .../xtradb-cluster-5.7.18.ebuild clean install':

gcs/src/gcs_core.cpp:815:5: note: here
     default:
     ^~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [gcs/src/.garb/gcs_core.o] Error 1
scons: building terminated because of errors.
cp: cannot stat 'garb/garbd': No such file or directory
cp: cannot stat 'libgalera_smm.so': No such file or directory
>>> Source compiled.
>>> Test phase [not enabled]: dev-db/xtradb-cluster-5.7.18

>>> Install xtradb-cluster-5.7.18 into /var/tmp/portage/dev-db/xtradb-cluster-5.7.18/image/ category dev-db
tar: *.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
/var/tmp/portage/dev-db/xtradb-cluster-5.7.18/temp/environment: line 511: cd: Percona-XtraDB-Cluster-*: No such file or directory
!!! dosbin: bin/mysqld does not exist
dosbin failed
rm: cannot remove 'bin/mysqld': No such file or directory
!!! dobin: bin/* does not exist
dobin failed
!!! dolib: lib/*.so* does not exist
dolib failed
!!! dolib: lib/*.a does not exist
dolib failed
!!! dodoc: docs/* does not exist
dodoc failed
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'include/*'
doins failed
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'man/*'
doins failed
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'share/*'
doins failed
>>> Completed installing xtradb-cluster-5.7.18 into /var/tmp/portage/dev-db/xtradb-cluster-5.7.18/image/

 * Final size of build directory: 642928 KiB (627.8 MiB)
 * Final size of installed tree:       8 KiB

 * QA Notice: file does not exist:
 *
 *      dosbin: bin/mysqld does not exist
 *      dobin: bin/* does not exist
 *      dolib: lib/*.so* does not exist
 *      dolib: lib/*.a does not exist
 *      dodoc: docs/* does not exist
 * QA Notice: #!/sbin/runscript is deprecated, use #!/sbin/openrc-run instead:
 *    //etc/init.d/mysql

**Comment by nfeutry** [comment]
percona has changed the build script, it only can be used with source code from git clone. 
We should change the ebuild to compile without this script.

**Comment by UnixRonin** [comment]
I've more recently been trying to build older versions, 5.6.32 and 5.6.41, and both 5.6 releases I have tried fail at the following step:

g++ -o garb/garb_config.os -c -Wold-style-cast -Weffc++ -pipe -Wno-long-long -Wno-deprecated -ansi -DPERCONA_INNODB_VERSION=rel78.1 -march=amdfam10 -O2 -pipe -mfpmath=sse -mcx16 -mpopcnt -g -O3 -fno-omit-frame-pointer -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -fPIC -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_TR1_ARRAY -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DOPENSSL_HAS_SET_ECDH_AUTO -DGCS_FOR_GARB -DGALERA_VER=\"3.28\" -DGALERA_REV=\"f216443\" -Iwsrep/src -I. -Icommon -Igalerautils/src -Igcs/src garb/garb_config.cpp
g++ -o gcs/src/.garb/gcs_params.o -c -pipe -Wno-long-long -Wno-deprecated -ansi -DPERCONA_INNODB_VERSION=rel78.1 -march=amdfam10 -O2 -pipe -mfpmath=sse -mcx16 -mpopcnt -g -O3 -fno-omit-frame-pointer -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-variadic-macros -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_TR1_ARRAY -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DOPENSSL_HAS_SET_ECDH_AUTO -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -DGCS_FOR_GARB -Iwsrep/src -Igalerautils/src -Igcomm/src -Igcache/src gcs/src/gcs_params.cpp
garb/garb_config.cpp:10:10: fatal error: wsrep_api.h: No such file or directory
 #include <wsrep_api.h>

(I manually modified a copy of the 5.6.32-25.17 ebuild to create a 5.6.41-28.28 ebuild.  I first had to delete and recreate the manifest, because the manifest in the ebuild contains an incorrect file size for Percona-XtraDB-Cluster-5.6.32-25.17.tar.gz.)

It appears to me that wsrep_api.h is present in the unpacked source tree, at /var/tmp/portage/dev-db/xtradb-cluster-5.6.32/work/percona-xtradb-cluster-Percona-XtraDB-Cluster-5.6.32-25.17/wsrep/wsrep_api.h, but is not being picked up by the build.  I'm completely unfamiliar with scons and have no idea how to fix that.


Is *ANY* version of this ebuild *currently known* to work?  The poor quality of MariaDB Galera Cluster is driving me crazy, and I've been looking for a working XtraDB Cluster ebuild for years.

**Comment by nfeutry** [comment]
I managed to create a new ebuild for 5.6.44, it should build correctly without any error.
```Server version: 5.6.44-86.0-28.34-log Percona XtraDB Cluster binary (GPL) 5.6.44-28.34, Revision, wsrep_28.34```
